[build-system]

requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]

name = "qmate"
version = "0.0.1"
description = "Create asynchronous and asynchronous task queues that run on a schedule... symantically"
long_description = "file: README.md"
long_description_content_type = "text/markdown"
author = "Digital Kelvin"
author_email = "your.email@example.com"
url = "https://github.com/digitalkelvin/qmate"
classifiers = []

[tool.setuptools.dependencies]
python_requires = ">=3.8"
install_requires = []

[tool.setuptools.packages]
find = {}

[tool.setuptools.package_data]
"*" = ["README.md"]

[tool.setuptools.options]
